version: '3.8'

services:
  frontend:
    image: petclinic-frontend:latest
    container_name: petclinic-frontend
    ports:
      - "80:8080"
    depends_on:
      - backend
    networks:
      - devops-network

  backend:
    image: petclinic-backend:latest
    container_name: petclinic-backend
    ports:
      - "9966:9966"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql,spring-data-jpa
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=petclinic
    depends_on:
      db:
        condition: service_healthy
    networks:
      - devops-network

  db:
    image: mysql:8
    container_name: petclinic-db
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppetclinic"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - devops-network
  prometheus:
    image: prom/prometheus
    container_name: petclinic-prometheus
    ports:
      - "9090:9090"
    volumes:
      - /var/lib/docker/volumes/jenkins_home/_data/workspace/petclinic-backend-pipeline/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - devops-network

  grafana:
    image: grafana/grafana
    container_name: petclinic-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - devops-network
volumes:
  db-data:

networks:
  devops-network:
    external: true
